name: Pull Code to Local

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  pull-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull code to local
      run: |
        if [[ "$OSTYPE" == "darwin"* || "$OSTYPE" == "linux-gnu" ]]; then
          ./pull.sh
        elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
          powershell -ExecutionPolicy Bypass -File pull.ps1
        else
          echo "Unsupported OS: $OSTYPE"
          exit 1
        fi
