name: Pull Code to Local

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  pull-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull code to local
      run: |
        git pull origin main  # Change 'main' to your branch name
